cert-manager:
  installCRDs: true
  resources:
    requests:
      cpu: 200m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 300Mi
  webhook:
    resources:
      requests:
        cpu: 200m
        memory: 35Mi
      limits:
        cpu: 300m
        memory: 100Mi
  cainjector:
    resources:
      requests:
        cpu: 200m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 300Mi
