apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters: 
            selector:
              matchLabels:
                nginx:  enabled
          - git:
              repoURL: https://github.com/akselleirv/argocd-playground.git
              revision: HEAD
              files:
              - path: "clusters/cluster-a/nginx/config.json"
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/akselleirv/argocd-playground.git
        targetRevision: HEAD
        path: 'charts/nginx'
        helm:
          releaseName: nginx
          valueFiles:
            - values.yaml
          values: |
            replicas: {{ .replicas }}
      destination:
        server: '{{server}}'
        namespace: nginx-ingress-controller
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true