apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
  # - clusters: 
  #     selector:
  #       matchLabels:
  #         nginx:  enabled
    - git:
        repoURL: https://github.com/akselleirv/argocd-playground.git
        revision: HEAD
        files:
        - path: clusters/cluster-a/nginx/config.yaml
    # - matrix:
    #     generators:
    #       - git:
    #           repoURL: https://github.com/akselleirv/argocd-playground.git
    #           revision: HEAD
    #           files:
    #           - path: "clusters/cluster-a/nginx/config.json"
    #       - clusters: 
    #           selector:
    #             matchLabels:
    #               nginx:  enabled
  template:
    metadata:
      name: 'nginx'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/akselleirv/argocd-playground.git
        targetRevision: HEAD
        path: 'charts/nginx'
        helm:
          releaseName: nginx-{{ .replicas }}
          valueFiles:
            - values.yaml
          # values: |
          #   replicas: {{ .replicas }}
      destination:
        server: https://cluster-a-control-plane:6443
        namespace: nginx-ingress-controller
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true